sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123
  redis:
    host: localhost
    port: 6379
    password:
    database: 10
  wechat:
    appid: 'wxb5fecdc4f511f5ba'           # 替换为空字符串
    secret: '99fc07d33ec9d026933621230225f34c'       # 替换为空字符串
    #    以下字段需要营业资质获取，目前实现的是模拟微信支付可以不用下面字段
    mchid: 1888888
    mchSerialNo: 4B3B3DC35414*****55BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php
  shop:
    address: 北京市朝阳区新街大道一号楼8层
  baidu:
    ak: CBx25UuorE2gl2AtAHiNzWTGE8l11Cqf
    sk: 申请百度地图api开启sn效验获取
  #阿里云oss存储配置，目前实现本地存储，不需要配置
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: 申请阿里云oss存储获取
    access-key-secret: 申请阿里云oss存储获取
    bucket-name: 存储桶名称

file:
  upload-path: ${user.dir}/sky-server/images/ #本地存储菜品图片地址

requestHeader: http://localhost:8080/images/ #前端获取菜品图片地址

